import { useState } from 'react'
import { Navigate } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext'
import s from './Profile.module.css'

export default function Profile({admin=false}){const {user,ready,updateProfile,changePassword,requestAccountDeletion}=useAuth();const [profileMessage,setProfileMessage]=useState('');const [passwordMessage,setPasswordMessage]=useState('');const [deleteMessage,setDeleteMessage]=useState('');const [busy,setBusy]=useState('')
 if(!ready)return <p>Loading profile…</p>;if(!user)return <Navigate to={admin?'/admin/login':'/login'} replace/>
 async function saveProfile(event){event.preventDefault();setBusy('profile');setProfileMessage('');try{const data=await updateProfile(Object.fromEntries(new FormData(event.currentTarget)));setProfileMessage(data.message||'Profile updated successfully.')}catch(e){setProfileMessage(e.message)}finally{setBusy('')}}
 async function savePassword(event){event.preventDefault();setBusy('password');setPasswordMessage('');const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));if(values.newPassword!==values.confirmPassword){setPasswordMessage('New passwords do not match.');setBusy('');return}try{const {data}=await changePassword(values);setPasswordMessage(data.message);form.reset()}catch(e){setPasswordMessage(e.message)}finally{setBusy('')}}
 async function requestDeletion(){if(!window.confirm('Request permanent deletion of your account and all associated data?'))return;setBusy('delete');try{const {data}=await requestAccountDeletion();setDeleteMessage(data.message)}catch(e){setDeleteMessage(e.message)}finally{setBusy('')}}
 return <div className={`${s.profile} ${admin?s.admin:''}`}><header><span>ACCOUNT SETTINGS</span><h1>Manage your profile</h1><p>Keep your identity and sign-in information current.{!admin&&' Name and email changes require administrator approval.'}</p></header><div className={s.grid}><form onSubmit={saveProfile}><h2>Profile details</h2><label>Display name<input name="name" defaultValue={user.name} minLength="2" maxLength="100" required autoComplete="name"/></label><label>Email address<input name="email" type="email" defaultValue={user.email} required autoComplete="email"/></label>{profileMessage&&<p role="status">{profileMessage}</p>}<button disabled={busy==='profile'}>{busy==='profile'?'Saving…':admin?'Save profile':'Request profile change'}</button></form><form onSubmit={savePassword}><h2>Change password</h2><label>Current password<input name="currentPassword" type="password" required autoComplete="current-password"/></label><label>New password<input name="newPassword" type="password" required minLength="8" autoComplete="new-password"/></label><label>Confirm new password<input name="confirmPassword" type="password" required minLength="8" autoComplete="new-password"/></label>{passwordMessage&&<p role="status">{passwordMessage}</p>}<button disabled={busy==='password'}>{busy==='password'?'Updating…':'Update password'}</button></form></div>{!admin&&<section className={s.danger}><h2>Delete account</h2><p>Request permanent deletion of your account, sessions, comments, saves, follows, and likes. An administrator must confirm this irreversible action.</p>{deleteMessage&&<p role="status">{deleteMessage}</p>}<button disabled={busy==='delete'} onClick={requestDeletion}>{busy==='delete'?'Sending request…':'Request account deletion'}</button></section>}</div>}
