import { Link } from 'react-router-dom'
import { useState } from 'react'
import Newsletter from '../../components/Newsletter'
import Icon from '../../components/Icon'
import s from './Info.module.css'
export default function Info({type}) {
 const [message,setMessage]=useState('')
 if(type==='newsletter')return <div className={s.info}><div className={s.eyebrow}>THE DAILY BRIEF</div><h1>Your world.<br/>A little clearer.</h1><p>Make space for a thoughtful start to your day. Our morning briefing brings together the ideas, stories, and perspectives worth your attention.</p><Newsletter wide/><p className={s.demoNote}>Newsletter preview: preferences are saved locally. Email delivery is not connected yet.</p></div>
 if(type==='contact')return <div className={s.info}><div className={s.eyebrow}>LET’S TALK</div><h1>Every conversation<br/>starts somewhere.</h1><p>Have a story idea, a question, or a different perspective? We’d like to hear it.</p><form className={s.contactForm} onSubmit={e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));localStorage.setItem('wbn-contact-draft',JSON.stringify(data));setMessage('Your message is saved as a draft on this device. Sending will be available when our contact service is connected.')}}><label>Your name<input name="name" required autoComplete="name"/></label><label>Email address<input name="email" type="email" required autoComplete="email"/></label><label>What’s on your mind?<select name="subject"><option>Share a story idea</option><option>General enquiry</option><option>Partnerships</option><option>Corrections and feedback</option></select></label><label>Your message<textarea name="message" rows="6" required/></label><button className="darkButton">Save message draft <Icon name="arrow" size={16}/></button><small>Preview form — messages are saved on your device and are not sent.</small>{message&&<p role="status">{message}</p>}</form></div>
 if(type==='privacy')return <div className={s.info}><div className={s.eyebrow}>YOUR PRIVACY MATTERS</div><h1>A transparent<br/>reading experience.</h1><p>This frontend preview stores saved article IDs, newsletter preferences, and any contact draft in your browser’s local storage. These details are not sent to a publication server.</p><h2>External services</h2><p>Images load from Unsplash and the typeface loads from Google Fonts. Your browser connects to those services when the site is viewed. This preview has no analytics or advertising integration.</p><h2>Your choices</h2><p>You can remove individual saved stories in your reading room. Use the button below to remove newsletter preferences and contact drafts from this device.</p><button className="darkButton" onClick={()=>{localStorage.removeItem('wbn-newsletter');localStorage.removeItem('wbn-contact-draft');setMessage('Newsletter preferences and contact drafts have been cleared.')}}>Clear preferences and drafts</button>{message&&<p role="status">{message}</p>}<p className={s.demoNote}>This page describes the current demo. A production privacy policy will need to reflect the services added at launch.</p></div>
 if(type==='notfound')return <div className={s.empty}><div className={s.eyebrow}>404 · A LITTLE OFF THE MAP</div><h1>Let’s find your next story.</h1><p>The page you’re looking for doesn’t exist.</p><Link className="darkButton" to="/">Back to the front page <Icon name="arrow"/></Link></div>
 return <div className={s.info}><div className={s.eyebrow}>ABOUT WORLD BRIEF NETWORK</div><h1>A wider world.<br/>A fresh perspective.</h1><p className={s.lead}>We believe the best stories don’t just keep you informed. They help you see things differently.</p><img className={s.aboutImage} src="https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=85" alt="People sharing ideas around a table"/><h2>Curiosity connects us.</h2><p>WorldBriefNetwork is a magazine concept for curious minds. From the ways our cities are changing to the creative ideas shaping everyday life, we make room for a broader conversation.</p><p>Our ambition is simple: clear writing, thoughtful perspectives, and a reading experience that respects your time. This preview brings that vision to life with sample editorial content.</p><div className={s.values}><div><span>01</span><h3>See the bigger picture</h3><p>Context makes a story meaningful.</p></div><div><span>02</span><h3>Stay thoughtfully curious</h3><p>Better questions open new doors.</p></div><div><span>03</span><h3>Keep it human</h3><p>People are at the heart of every story.</p></div></div><Link className="darkButton" to="/contact">Get in touch <Icon name="arrow"/></Link><Newsletter wide/></div>
}
