import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { stories, articleBody } from '../data/stories'
import Icon from '../components/Icon'
import StoryCard from '../components/StoryCard'
import Newsletter from '../components/Newsletter'
import s from './Pages.module.css'
export default function Article({saved,onSave}) {
 const {id}=useParams();const story=stories.find(x=>x.id===id);const [shared,setShared]=useState('')
 if(!story)return <div className={s.empty}><h1>Story not found</h1><Link className="darkButton" to="/">Back to the front page</Link></div>
 async function share(){try{await navigator.clipboard.writeText(window.location.href);setShared('Link copied')}catch{setShared('Copy the page address to share this story')}}
 return <><article className={s.article}><Link className={s.breadcrumb} to={`/category/${story.category.toLowerCase()}`}>Home / {story.category}</Link><div className={s.articleHeading}><span className={s.eyebrow}>{story.category} · THE BIG PICTURE</span><h1>{story.title}</h1><p>{story.description}</p><div className={s.articleMeta}><span className={s.avatar}>{story.author.split(' ').map(x=>x[0]).join('')}</span><div><strong>{story.author}</strong><small>September 15, 2026 · {story.time}</small></div><button onClick={()=>onSave(id)} aria-pressed={saved.includes(id)}><Icon name="bookmark" fill={saved.includes(id)?'currentColor':'none'}/>{saved.includes(id)?'Saved':'Save story'}</button><button onClick={share}><Icon name="share"/> Share</button></div>{shared&&<div role="status" className={s.shareNotice}>{shared}</div>}</div><figure className={s.articleImage}><img src={story.image} alt={story.title}/><figcaption>Photo: Unsplash · Editorial illustration</figcaption></figure><div className={s.articleBody}><span className={s.demoNote}>EDITORIAL PREVIEW · SAMPLE ARTICLE</span>{articleBody(story).map((p,i)=><p key={p} className={i===0?s.firstParagraph:''}>{p}</p>)}<blockquote>Stay curious. Ask better questions. See the bigger picture.</blockquote><p>WorldBriefNetwork brings a thoughtful perspective to the stories that connect us. Explore more from our {story.category.toLowerCase()} desk below.</p><Link to={`/category/${story.category.toLowerCase()}`} className="darkButton">More in {story.category} <Icon name="arrow" size={15}/></Link></div></article><section><div className={s.sectionHeading}><h2><span/> Keep your curiosity going</h2></div><div className={s.threeGrid}>{stories.filter(x=>x.id!==id).slice(0,3).map(x=><StoryCard story={x} key={x.id} saved={saved} onSave={onSave}/>)}</div></section><Newsletter wide/></>
}
