import { useState } from 'react'
import { BrowserRouter, Routes, Route } from 'react-router-dom'
import Layout from './components/Layout'
import Seo from './components/Seo'
import Preloader from './components/Preloader/Preloader'
import { AuthProvider } from './context/AuthContext'
import Home from './pages/Home/Home'
import Listing from './pages/Listing/Listing'
import Article from './pages/Article/Article'
import Info from './pages/Info/Info'
import Auth from './pages/Auth/Auth'
import ForgotPassword from './pages/ForgotPassword/ForgotPassword'
export default function App(){const [saved,setSaved]=useState(()=>{try{const value=JSON.parse(localStorage.getItem('wbn-saved')||'[]');return Array.isArray(value)?value:[]}catch{return []}});function onSave(id){setSaved(previous=>{const next=previous.includes(id)?previous.filter(x=>x!==id):[...previous,id];localStorage.setItem('wbn-saved',JSON.stringify(next));return next})}const props={saved,onSave};return <AuthProvider><Preloader/><BrowserRouter><Seo/><Routes><Route element={<Layout saved={saved}/>}><Route index element={<Home {...props}/>}/><Route path="category/:category" element={<Listing {...props}/>}/><Route path="article/:id" element={<Article {...props} key={window.location.pathname}/>}/><Route path="login" element={<Auth mode="login"/>}/><Route path="signup" element={<Auth mode="signup"/>}/><Route path="forgot-password" element={<ForgotPassword/>}/>{['search','saved','trending'].map(type=><Route key={type} path={type} element={<Listing type={type} {...props}/>}/>)}{['about','contact','privacy','newsletter'].map(type=><Route key={type} path={type} element={<Info key={type} type={type}/>}/>)}<Route path="*" element={<Info type="notfound"/>}/></Route></Routes></BrowserRouter></AuthProvider>}
