import { useEffect, useState } from 'react'
import { createAuthor, deleteAuthor, getAuthors, saveAuthor } from './adminApi'
import s from './Admin.module.css'
import a from './Authors.module.css'

const empty={name:'',slug:'',bio:'',isActive:true,manualLikeCount:0,manualFollowerCount:0}
export default function Authors(){
 const [rows,setRows]=useState([]);const [editing,setEditing]=useState(null);const [form,setForm]=useState(empty);const [error,setError]=useState('');const [busy,setBusy]=useState(false)
 const load=()=>getAuthors().then(({data})=>setRows(data)).catch(e=>setError(e.message));useEffect(()=>{load()},[])
 function begin(row){setEditing(row.id);setForm({name:row.name,slug:row.slug,bio:row.bio||'',isActive:row.isActive,manualLikeCount:row.manualLikeCount,manualFollowerCount:row.manualFollowerCount})}
 async function submit(event){event.preventDefault();setBusy(true);setError('');try{if(editing)await saveAuthor(editing,form);else await createAuthor(form);setEditing(null);setForm(empty);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function remove(row){if(!window.confirm(`Delete ${row.name}?`))return;try{await deleteAuthor(row.id);await load()}catch(e){setError(e.message)}}
 return <><header className={s.pageHeader}><div><small>NEWSROOM</small><h1>Authors</h1><p>Manage public profiles, likes, followers, and publishing availability.</p></div></header>{error&&<div className={s.error} role="alert">{error}</div>}
 <form className={a.form} onSubmit={submit}><div><strong>{editing?'Edit author':'Add author'}</strong><small>Profile details and totals appear publicly.</small></div><div className={a.fields}><label>Name <input aria-label="Author name" required minLength="2" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Slug <input aria-label="Author slug" value={form.slug} placeholder="generated-from-name" onChange={e=>setForm({...form,slug:e.target.value})}/></label><label className={a.wide}>Biography <textarea aria-label="Author biography" value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})}/></label><label>Additional likes <input aria-label="Additional likes" type="number" min="0" value={form.manualLikeCount} onChange={e=>setForm({...form,manualLikeCount:Number(e.target.value)})}/></label><label>Additional followers <input aria-label="Additional followers" type="number" min="0" value={form.manualFollowerCount} onChange={e=>setForm({...form,manualFollowerCount:Number(e.target.value)})}/></label>{editing&&<label><span>Profile status</span><span><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> Active profile</span></label>}</div><div className={a.actions}><button className={a.primary} disabled={busy}>{busy?'Saving…':editing?'Save author':'Add author'}</button>{editing&&<button className={a.cancel} type="button" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}</div></form>
 <div className={s.tableWrap}><table><thead><tr><th>Author</th><th>Likes</th><th>Followers</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.name}</strong><small>/{row.slug}<br/>{row.bio||'No biography yet.'}</small></td><td>{row.likeCount}</td><td>{row.followerCount}</td><td>{row.isActive?'Active':'Inactive'}</td><td><div className={a.rowActions}><button className={a.edit} onClick={()=>begin(row)}>Edit</button><button className={a.delete} onClick={()=>remove(row)}>Delete</button></div></td></tr>)}</tbody></table></div></>
}
